stages:
  - test
  - deploy

deploy:
  image: maven:3.8.1-openjdk-8
  stage: deploy
  needs: []
  script:
    - sed -i 's/https:\/\/oss.sonatype.org\/service\/local\/staging\/deploy\/maven2\//https:\/\/gitlab.com\/api\/v4\/projects\/29206055\/packages\/maven/g' pom.xml
    - sed -i 's/https:\/\/gitlab.com\/api\/v4\/projects\/29199582\/packages\/maven/https:\/\/gitlab.com\/api\/v4\/projects\/29206055\/packages\/maven/g' pom.xml
    - sed -i 's/ossrh/gitlab/g' pom.xml
    - TEXT='${appenders.rawVersion}${appenders.releaseType}'
    - sed -i "s/<appenders.version>${TEXT}<\/appenders.version>/<appenders.version>$CI_COMMIT_REF_SLUG-SNAPSHOT<\/appenders.version>/g" pom.xml
    - mvn --batch-mode --update-snapshots -s gitlab_deployment.xml -Dgpg.skip -Dappenders.deploy.gitlabToken=$CI_JOB_TOKEN -Dappenders.deploy.gitlabUsername=Job-Token deploy
  rules:
    - if: $CI_PROJECT_NAME == "Appenders-Branch"

# Disabled in the Appenders-Branch project via repository variables
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml

