name: Deploy

on: [ push, workflow_dispatch ]

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    environment: sonatype
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Deploy with Maven
        run: mvn --batch-mode --update-snapshots -Dappenders.releaseType= deploy
        env:
          OSSRH_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  deploy_snapshot:
    runs-on: ubuntu-latest
    environment:
      name: gitlab-snapshot
      url: https://gitlab.com/taucher2003-group/appenders/-/packages
    if: ${{ github.ref == 'refs/heads/development' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: Change distribution location
        run: sed -i 's/https:\/\/oss.sonatype.org\/service\/local\/staging\/deploy\/maven2\//https:\/\/gitlab.com\/api\/v4\/projects\/29199582\/packages\/maven/g' pom.xml
      - name: Change distribution name
        run: sed -i 's/ossrh/gitlab/g' pom.xml
      - name: Deploy with Maven
        run: mvn --batch-mode --update-snapshots -s gitlab_deployment.xml -Dgpg.skip -Dappenders.deploy.gitlabToken=${{ secrets.GITLAB_TOKEN }} -Dappenders.deploy.gitlabUsername=Deploy-Token deploy
  deploy_commit:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    environment:
      name: gitlab-commit
      url: https://gitlab.com/taucher2003-group/appenders-commit/-/packages
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: Change distribution location
        run: sed -i 's/https:\/\/oss.sonatype.org\/service\/local\/staging\/deploy\/maven2\//https:\/\/gitlab.com\/api\/v4\/projects\/29200088\/packages\/maven/g' pom.xml
      - name: Change distribution name
        run: sed -i 's/ossrh/gitlab/g' pom.xml
      - name: Change version
        run: sed -i 's/<appenders.version>${appenders.rawVersion}${appenders.releaseType}<\/appenders.version>/<appenders.version>${{ github.sha }}<\/appenders.version>/g' pom.xml
      - name: Deploy with Maven
        run: mvn --batch-mode --update-snapshots -s gitlab_deployment.xml -Dgpg.skip -Dappenders.version=${{ github.sha }} -Dappenders.deploy.gitlabToken=${{ secrets.GITLAB_TOKEN }} -Dappenders.deploy.gitlabUsername=Deploy-Token deploy