name: Deploy

on: [ push, workflow_dispatch ]

jobs:
  deploy_release:
    runs-on: ubuntu-latest
    environment: sonatype
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Deploy with Maven
        run: mvn --batch-mode --update-snapshots -Dappenders.releaseType= deploy
        env:
          OSSRH_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  deploy_snapshot:
    runs-on: ubuntu-latest
    environment: gitlab
    if: ${{ github.ref == 'refs/heads/development' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          server-id: gitlab
          server-username: GITLAB_USERNAME
          server-password: GITLAB_PASSWORD
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Deploy with Maven
        run: mvn --batch-mode --update-snapshots deploy
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  deploy_commit:
    runs-on: ubuntu-latest
    environment: gitlab
    if: ${{ github.ref != 'refs/heads/development' && github.ref != 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          server-id: gitlab
          server-username: GITLAB_USERNAME
          server-password: GITLAB_PASSWORD
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Deploy with Maven
        run: mvn --batch-mode --update-snapshots -Dappenders.version=${{ github.sha }} deploy
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
#  deploy_branch:
#    runs-on: ubuntu-latest
#    environment: gitlab
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: 11
#          distribution: temurin
#          server-id: gitlab
#          server-username: GITLAB_USERNAME
#          server-password: GITLAB_PASSWORD
#          gpg-private-key: ${{ secrets.GPG_KEY }}
#      - name: Deploy with Maven
#        run: mvn --batch-mode --update-snapshots -Dappenders.version=${{ github.ref }}-SNAPSHOT deploy
#        env:
#          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
#          GITLAB_PASSWORD: ${{ secrets.GITLAB_TOKEN }}